### ISSUE TITLE
"Send & Transfer" button is not working properly

### ISSUE THREAD

**Issue by anee786** [ExpandedVenture/ConnectionSphere#233]
The client: lerichemarketing@gmail.com was pressing "Send & transfer" button to transfer the lead but either the message got pending or was cancelled. 
I pressed "transfer" button for the same lead and it got transferred as you can see in the screenshot below

![image](https://user-images.githubusercontent.com/76562101/154534469-d3363002-6c7b-4f11-a05e-ff368ec8e0fb.png)

**Comment by leandrosardi** [comment]
Hello @anee786 

There is not any glith in the "Transfer" button.

That message was cancelled faily, because it was stuck stuck for a long time due this other issue: #232 , and the lead sent us a message before we could resolve that glich and deliver the stuck message.

Here is the technical information:

## Query

```sql
use euler;

select h.create_time, h.inmessage_end_time, h.direction, h.body
from lnchat h
where h.id_result='E7AD70E1-8B69-455C-B3D0-9B197018A3BE'
order by h.create_time
```

## Results

![image](https://user-images.githubusercontent.com/55877846/154699973-290523cc-0a4d-4815-836f-2f246c3fb057.png)

**Comment by leandrosardi** [comment]
I am closing this issue now.
