### ISSUE TITLE
Bogus email notification reported by the client

### ISSUE THREAD

**Issue by anee786** [ExpandedVenture/ConnectionSphere#235]
This client eshopadventures@gmail.com is reporting that he has received bogus email about this leads. Because this lead has never sent any message from last 17 days. ( I have checked on linkedin account too, and client is right)

![image](https://user-images.githubusercontent.com/76562101/155596464-7e68b478-7dfa-49eb-a95a-3d7c1866834c.png)

**Comment by leandrosardi** [comment]
UPDATE:

@anee786 
Inform the client that this glitch will take us one more day, and it will be fixed by next Monday.

---- 
I can find the lead George Boyadzhyan, as you can see in the link below:
https://euler.connectionsphere.com/prospecting/responses?drl.responses.folder=0&drl.responses.id_pipeline=&drl.responses.profile_name=George%20Boya

![image](https://user-images.githubusercontent.com/55877846/155741627-377fc21d-7b6f-4413-81ef-7d90cb0e66b4.png)

BTW, this client has all his pipelines paused, as you can see in the pic below.
Please ask him if that is fine?
![image](https://user-images.githubusercontent.com/55877846/155741341-b0383a60-1af7-446c-a9d6-63f8f0f33fa1.png)

**Comment by leandrosardi** [comment]
Resuming to check this issue.

**Comment by leandrosardi** [comment]
UPDATE:

1. The sales assistant has a different name in its profile.

2. The whole conversations of this sales assistant are scraped wrongly, as is shown in the picture below.

3. Each time a  scrape the inbox, a new bogus message is added to the database, and an email notification is delivered to the client.

![image](https://user-images.githubusercontent.com/55877846/155894446-6c87d1c8-180a-486a-ad53-dac9985d3c1b.png)

![image](https://user-images.githubusercontent.com/55877846/155894453-f24e82ef-9b0f-445d-ac73-c6d1820d3dc1.png)

**Comment by leandrosardi** [comment]
This issue was happening when the name of our sales assistant was not exactly the same than the name registered in our database.

I just pushed a partial patch that will resolve the problem by now, but it is not a complete solution for long term.

https://github.com/leandrosardi/tempora/commit/1e53a87acbac38116eddea974e470d93bcf06f8c

https://github.com/leandrosardi/tempora/commit/15d62f33e891296c71f63501e063ce0ed8f55c78

**Comment by leandrosardi** [comment]
# Query

Use this query to check if this issue is still happening.

```sql
use euler;

/*
 * This query is to find accounts with repetitive chats 
 *
 *
 */
select top 1 c.name, u.username, p.name
from lnchat h with (nolock)
join lnuser u with (nolock) on u.id=h.id_lnuser
join [result] r with (nolock) on r.id=h.id_result
join search s with (nolock) on s.id=r.id_search
join [user] e with (nolock) on e.id=s.id_user
join client c with (nolock) on c.id=e.id_client
join [profile] p with (nolock) on p.id=r.id_profile
where h.create_time > dateadd(hh,-24,getdate())
and exists (
	select i.id
	from lnchat i with (nolock)
	where i.id_result=h.id_result
	and i.id<>h.id
	and cast(i.body as varchar(5000)) = cast(h.body as varchar(5000))
)
```

**Comment by leandrosardi** [comment]
@anee786 
This issue has been fixed 1 week ago.
